#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gres=gpu:ampere_a100:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --time=48:00:00
#SBATCH --account=su007-ndmh-gpu
#SBATCH --job-name=WWSAP
#SBATCH --mem=0
#SBATCH -o "domain_wall_WWSAP.out"
module purge; module load GCC/11.3.0 CUDA/11.7.0 OpenMPI/4.1.4 PyTorch/2.0-Miniconda3-4.12.0 SciPy-bundle

[ ! -z "$SLURM_ARRAY_TASK_ID" ] && export LOGSUFFIX="_"$SLURM_ARRAY_TASK_ID
export OMP_NUM_THREADS=32

python domain_wall_cost.py W W S AP 

